#当前服务的其他配置信息（注册中心地址等等
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G4GwAfYSzts2hpHZcze
      secret-key: S9rTagkicAEP2hf97GIwOhgx9DCCaC
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: cmall-chrisz
      sms:
        host: https://intlsms.market.alicloudapi.com
        path: /comms/sms/sendmsgall
        appcode: 7aad0c2b7f1640669016a8d53ea3a6bf
        templateID: 20201204161320

  application:
    name: cmall-third-server

server:
  port: 30000

